name: DHProfileDev

services:
  server:
    image: hugomods/hugo:debian-base-non-root
    command: server -D --poll 700
    volumes:
      - ./:/src
      - ~/hugo_cache:/tmp/hugo_cache
    ports:
      - 1313:1313
